### PR TITLE
Added image dimension into Format String

### PR DESCRIPTION
**Pull request by paulmassen**
This is a suggestion I made a few weeks ago https://github.com/ronakg/smart-image-renamer/issues/4
This is my first time messing with python, so the syntax might not be the best and it might be worth having a second look at this, but it works fine apparently.

### CODE REVIEW

**Review by ronakg — APPROVED** [review]
Looks good to me.

**Comment by ronakg** [comment]
Can you please update the readme file as well?

**Comment by paulmassen** [comment]
Done!
Btw, it looks like a lacks of timestamp on an image prevent the renamer from running, even if the timestamp is not used on the final file name. Is that on purpose?

**Comment by ronakg** [comment]
Main purpose of the script was to fetch timestamp from image and use that. So didn't make sense to continue if timestamp was missing.

But I see your point. If it's not used, then we shouldn't worry about it being not present.

**Pull request merged**
